spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/milestone_db
    username: milestone_user
    password: milestone_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
server:
  port: 8080
logging:
  level:
    root: INFO
    com.example.project: DEBUG
